[package]
name = "debrief-tts"
version.workspace = true
edition.workspace = true

[dependencies]
cpal = "0.18.2"
debrief-core = { version = "0.1.0", path = "../debrief-core" }
ort = { version = "2.0.0-rc.7", features = ["ndarray"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
unicode-normalization = "0.1.24"
